version: "3"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: frontend
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - app
    depends_on:
      - backend
    env_file:
    - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app
    depends_on:
      - database
    env_file:
    - ./backend/.env

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    volumes:
    - database:/var/lib/postgresql/data
    networks:
      - app
    env_file:
    - ./database/docker.env  

volumes:
  database:
    driver: local

networks:
  app:
    driver: bridge