name: AWS EC2 instance deploy

on:
  workflow_run:
    workflows: ["Frontend CI", "Backend CI", "Database CI"]
    types: [completed]

jobs:


  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 

    steps:
    - 
      name: Connect to EC2 via SSH and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_EC2_HOST }}  
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22 
        script: |
          cd /home/ubuntu
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker image prune -af
# jobs:

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - 
#       name: AWS SSM Send-Command
#       uses: peterkimzz/aws-ssm-send-command@v1.1.1
#       with:
#         # AWS access key id
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         # AWS secret access key
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         # Where EC2 instance is
#         aws-region: ${{ secrets.AWS_REGION }}
#         # AWS EC2 Instance id or ids
#         instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
#         # Command execution location
#         working-directory: /home/ubuntu
#         # Bash commands to execute
#         command: |
#           sudo docker-compose stop
#           sudo docker-compose rm -f
#           sudo docker-compose pull
#           sudo docker-compose up -d
#           sudo docker image prune -af
#         # Comment for Send-Command
#         comment: docker-compose.yml file re-pulls newer versions of gym14 images and runs them on the instance