name: AWS CD

on:
  workflow_run:
    workflows: ["Frontend CI", "Backend CI", "Database CI"]
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 

    steps:
    - 
      name: Connect to EC2 via SSH and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_EC2_HOST }}  
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22 
        script: |
          set -e
          cd /home/ubuntu
          sudo docker compose stop
          sudo docker compose rm -f
          sudo docker compose pull
          sudo docker compose up -d
          sudo docker image prune -af