name: Backend CI

on:
  push:
    branches:
      - 'never-exists'  # Ветка, которая не существует и не будет существовать

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow does nothing"