name: Database CI

on: 
  push:
    branches:
      - main
    paths:
      - database/**
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - database/**

jobs:

  docker:
    name: Docker build and publish
    runs-on: ubuntu-latest

    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_TWO }}
    - 
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./database
        file: ./database/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gym-database:latest